# -*- coding: utf-8 -*-
"""computeSales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q72DLNclddi5-lkaCHiIR5hKYrs5PeKL
"""

pip install pylint

!pylint computeSales.ipynb

pip install flake8

!jupyter nbconvert --to script computeSales.ipynb

!flake8 computeSales.ipynb

from google.colab import drive
drive.mount('/content/drive')

import os
DIR = "/content/drive/MyDrive/Maestría Inteligencia Artificial Aplicada/PS y AC"
os.chdir(DIR)

import json
import pandas as pd


def func_ventas(catalogo, ventas):
    # Catálogo de productos
    with open(catalogo, 'r') as f:
        catalogo_prod = json.load(f)

    # Catálogo de ventas
    with open(ventas, 'r') as f:
        ventas_prod = json.load(f)

    catalogo_pd = pd.DataFrame(catalogo_prod)
    costo_total = 0

    for sale in ventas_prod:
        nom_prod = sale.get('Product')
        cantidad = sale.get('Quantity')
        if nom_prod in catalogo_pd['title'].values:
            prod = catalogo_pd.loc[catalogo_pd['title'] == str(nom_prod)]
            precio = prod.iloc[0]['price']  # Access price of the product
            costo_venta = precio * cantidad
            costo_total += costo_venta
            print(f"Producto vendido: {nom_prod}, "
                  f"Cantidad: {cantidad}, Costo total: ${costo_venta:.2f}")
        else:
            print(f"El producto {nom_prod} no se encontró en el catálogo.")

    # Imprimir el costo total
    print(f"Costo total de las ventas: ${costo_total:.2f}")

    # Escribir los resultados en SalesResults.txt
    with open("SalesResults.txt", 'w') as f:
        f.write("Resultados de ventas:\n")
        for sale in ventas_prod:
            nom_prod = sale.get('Product')
            cantidad = sale.get('Quantity')
            if nom_prod in catalogo_prod:
                prod = catalogo_prod[nom_prod]
                precio = prod.get('price')
                costo_venta = precio * cantidad
                f.write(f"Producto vendido: {nom_prod}, "
                        f"Cantidad: {cantidad}, Costo total: ${costo_venta:.2f}\n")
        f.write(f"Costo total de todas las ventas: ${costo_total:.2f}")

catalogo = 'TC1.ProductList.json'
ventas = 'TC1.Sales.json'

func_ventas(catalogo, ventas)

catalogo = 'TC1.ProductList.json'
ventas = 'TC2.Sales.json'

func_ventas(catalogo, ventas)

catalogo = 'TC1.ProductList.json'
ventas = 'TC3.Sales.json'

func_ventas(catalogo, ventas)

