# -*- coding: utf-8 -*-
"""wordCount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WUKCqe-d3cZlNNyzyMHmx68RU3GrzEoR
"""

pip install pylint

!pylint wordCount.ipynb

from google.colab import drive
drive.mount('/content/drive')

import sys
import os
DIR = "/content/drive/MyDrive/Maestría Inteligencia Artificial Aplicada/PS y AC"
os.chdir(DIR)

# PROCESADO DE ARCHIVOS
def procesar_archivo(tc):
    try:
        with open(tc, 'r') as archivo:
            contenido_archivo = archivo.read()
            print(contenido_archivo)
    except FileNotFoundError:
        print(f"Error: No se encontró el archivo: {tc}")
    except Exception as e:
        print(f"Error al procesar el archivo: {e}")

tc_seleccionado = 'TC1 - 3.txt'  # 'TC2.txt', 'TC3.txt', 'TC4.txt', 'TC5.txt', 'TC6.txt', 'TC7.txt'
procesar_archivo(tc_seleccionado)

# FUNCIÓN DE CONTEO

def procesar_archivo(tc):
    try:
        with open(tc, 'r') as archivo:
            contenido_archivo = archivo.read().lower().split()
            frecuencia_palabras = {}
            for palabra in contenido_archivo:
                if palabra in frecuencia_palabras:
                    frecuencia_palabras[palabra] += 1
                else:
                    frecuencia_palabras[palabra] = 1

            print("Palabras y su frecuencia en el archivo:")
            for palabra, frecuencia in frecuencia_palabras.items():
                print(f"{palabra}: {frecuencia}")

            with open('WordCountResults.txt', 'w') as resultado_file:
                resultado_file.write("Palabras y su frecuencia en el archivo:\n")
                for palabra, frecuencia in frecuencia_palabras.items():
                    resultado_file.write(f"{palabra}: {frecuencia}\n")
    except FileNotFoundError:
        print(f"Error: No se encontró el archivo: {tc}")
    except Exception as e:
        print(f"Error al procesar el archivo: {e}")

#PROCESADO DE ARCHIVO

tc_seleccionado = 'TC1 - 3.txt' # 'TC2 - 3.txt'   'TC3 - 3.txt'  'TC4 - 3.txt'  'TC5 - 3.txt'

# Procesar el archivo
procesar_archivo(tc_seleccionado)